Zadanie 6 4
mkosecki1/maciek-kosecki-kodilla-java pull request #3
Opened 2017-10-14 15:02 UTC by mkosecki1

Zgodnie z poleceniem w zadaniu 6.4. przygotowałem szkielet klas:
https://github.com/mkosecki1/maciek-kosecki-kodilla-java/tree/zadanie_6_4/kodilla-testing/src/main/java/com/kodilla/testing/shape

oraz napisałem testy:
https://github.com/mkosecki1/maciek-kosecki-kodilla-java/blob/zadanie_6_4/kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java

Czekam na sprawdzenie, żebym mógł uzupełnić metody.

2017-10-14 15:34 UTC, MARudnicki requested changes

2017-10-14 15:34 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertEquals(1,shapeCollector.showFigures());
Ten warunek jest niepoprawny. 
jesli shapeCollector.showFigures() zwroci liste obiektow w ShapeCollector i lista nie bedzie rowna 1
warunkiem moze byc np. 
 Assert.assertEquals(1,shapeCollector.showFigures().size());

2017-10-14 15:34 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        shapeCollector.addFigure(triangle);
Nie ma sensu dodawac do ShapeCollector 2x obiektu triangle. Raz przez konstruktor, drugi raz przez metode triangle.
W ShapeCollector nie ma potrzeby tworzyc konstruktor z argumentem. ShapeCollector powinien zawierac w sobie tylko liste obiektow Shape

2017-10-14 15:34 UTC, MARudnicki commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertEquals(0,shapeCollector.showFigures());
shapeCollector.showFigures().size()

2017-10-14 16:51 UTC, mkosecki1 commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertEquals(1,shapeCollector.showFigures());
ok, taki miałem zamysł, żeby na końcu było size() - ale jak widać nie dopisałem tego

2017-10-14 16:54 UTC, mkosecki1 commented on kodilla-testing/src/test/java/com/kodilla/testing/shape/ShapeCollectorTestSuite.java
> +        Assert.assertEquals(0,shapeCollector.showFigures());
ok

2017-10-15 08:01 UTC, mkosecki1 commented
Uzupełniłem już metody. Czekam na sprawdzenie i akceptację.

2017-10-15 15:37 UTC, merged