Zadanie 7 4
mkosecki1/maciek-kosecki-kodilla-java pull request #8
Opened 2017-10-21 14:19 UTC by mkosecki1

Exercise 7.4. to check out.

2017-10-21 18:06 UTC, mkosecki1 commented
I just add exercise 7.5.

2017-10-22 08:50 UTC, MARudnicki requested changes

2017-10-22 08:50 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +    private final String continent;
do zmiennej continent nie mozna sie odwolac. Albo dodaj getter albo usun zmienna

2017-10-22 08:50 UTC, MARudnicki commented on kodilla-stream/src/main/java/com/kodilla/stream/world/World.java
> +                .flatMap(country -> country.getCountries().stream())
nazwa country jest mylaca. Powinna byc
.flatMap(continent -> continent.getCountries().stream())

2017-10-22 11:25 UTC, mkosecki1 commented on kodilla-stream/src/main/java/com/kodilla/stream/world/Continent.java
> +    private final String continent;
ok, dodałem getter.

2017-10-22 11:27 UTC, mkosecki1 commented on kodilla-stream/src/main/java/com/kodilla/stream/world/World.java
> +                .flatMap(country -> country.getCountries().stream())
ok, poprawiłem.

2017-10-24 16:31 UTC, merged